### PR TITLE
Closes #2543 fix_queries_mh: fix script and improve error messages

### LINKED ISSUE #2543: Bug: Using `derive_vars_query` with admiral::ADMH and admiral::queries_mh  errors
### What happened?

While adopting the `data/data-raw` convention we were re-running old code and noticed that this code no longer worked

image

### Session Information

R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.5.1         lubridate_1.9.3       dplyr_1.1.4          
[4] pharmaversesdtm_1.0.0 admiral_1.1.1        

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5       cli_3.6.3         rlang_1.1.4       stringi_1.8.4    
 [5] purrr_1.0.2       generics_0.1.3    assertthat_0.2.1  glue_1.8.0       
 [9] rprojroot_2.0.4   hms_1.1.3         fansi_1.0.6       admiraldev_1.1.0 
[13] tibble_3.2.1      lifecycle_1.0.4   diffdf_1.1.1      compiler_4.3.3   
[17] fs_1.6.4          timechange_0.3.0  pkgconfig_2.0.3   tidyr_1.3.1      
[21] rstudioapi_0.17.0 R6_2.5.1          tidyselect_1.2.1  utf8_1.2.4       
[25] usethis_3.0.0     pillar_1.9.0      magrittr_2.0.3    tools_4.3.3      
[29] withr_3.0.1       desc_1.4.3  

### Reproducible Example

Please see the file in `data-raw` seen in the screenshot

## Definition of Done

- [x] Investigate source of the error and report back in this issue
- [x] Propose fix to the function and/or example datasets used.  
- [x] Implement fixes and Profit 💰 

@pharmaverse/admiral @pharmaverse/admiral_comm anyone familiar with these query datasets and want to take a peek please?

### PR DESCRIPTION
**Pull request by bundfussr**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF and a PNG version of it to the same folder. (The PNG version can be created by taking a screenshot of the PDF version.)
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

File: data-raw/create_queries_and_queries_mh.R [hunk 1]
```diff
@@ -5,6 +5,9 @@
 # SRCVAR, e.g., AEDECOD, AELLT, ...
 # TERMCHAR, non NULL
 
+library(dplyr) # nolint
+library(admiral) # nolint
```
Comment (bms63) [inline data-raw/create_queries_and_queries_mh.R:9]: Thinking on this - is this needed with the use of `::` and `:::`?

**Review by bms63 — APPROVED** [review]
This looks nice!! I don't have much to add!!

File: data-raw/create_queries_and_queries_mh.R (hunk 1 above)
Comment (bundfussr) [reply data-raw/create_queries_and_queries_mh.R]: You are right, we don't need to load admiral. I've removed it. Thanks.
