### PR TITLE
Closes #2481 bug the result of derive param tte depends on the sort order of the input

### LINKED ISSUE #2481: Bug: The result of `derive_param_tte()` depends on the sort order of the input
### What happened?

The result of `derive_param_tte()` depends on the sort order of the input. See example below.

An `order` argument should be added to `event_source()` and `censor_source()`. It should be defaulted to `NULL`. It expects a list of variables, which are used in addition to `date` for sorting the input data.

The `check_type` argument should be added to `derive_param_tte()` and defaulted to `"warning"`. The uniqueness of the selected records should be checked by calling `signal_duplicate_records()`.

### Session Information

_No response_

### Reproducible Example

```

adsl <- tibble::tribble(
  ~USUBJID, ~TRTSDT,           ~TRTEDT,           ~EOSDT,
  "01",     ymd("2020-12-06"), ymd("2021-03-02"), ymd("2021-03-06"),
  "02",     ymd("2021-01-16"), ymd("2021-01-20"), ymd("2021-02-03")
) %>%
  mutate(STUDYID = "AB42")

ae <- tibble::tribble(
  ~USUBJID, ~AESTDTC,     ~AESEQ, ~AEDECOD,
  "01",     "2021-01-03",      1, "Flu",
  "01",     "2021-03-04",      2, "Cough",
  "01",     "2021-01-03",      3, "Flu"
) %>%
  mutate(
    STUDYID = "AB42",
    AESTDT = ymd(AESTDTC)
  )

ttae <- event_source(
  dataset_name = "ae",
  date = AESTDT,
  set_values_to = exprs(
    EVENTDESC = "AE",
    SRCDOM = "AE",
    SRCVAR = "AESTDTC",
    SRCSEQ = AESEQ
  )
)

eot <- censor_source(
  dataset_name = "adsl",
  date = pmin(TRTEDT + days(10), EOSDT),
  censor = 1,
  set_values_to = exprs(
    EVENTDESC = "END OF TRT",
    SRCDOM = "ADSL",
    SRCVAR = "TRTEDT"
  )
)

derive_param_tte(
  dataset_adsl = adsl,
  start_date = TRTSDT,
  event_conditions = list(ttae),
  censor_conditions = list(eot),
  source_datasets = list(adsl = adsl, ae = arrange(ae, AESEQ)),
  set_values_to = exprs(
    PARAMCD = "TTAE"
  )
)
```
produces
```
# A tibble: 2 × 10
  USUBJID STUDYID EVENTDESC  SRCDOM SRCVAR  SRCSEQ  CNSR ADT        STARTDT    PARAMCD
  <chr>   <chr>   <chr>      <chr>  <chr>    <dbl> <int> <date>     <date>     <chr>  
1 01      AB42    AE         AE     AESTDTC      1     0 2021-01-03 2020-12-06 TTAE   
2 02      AB42    END OF TRT ADSL   TRTEDT      NA     1 2021-01-30 2021-01-16 TTAE   
```
but 
```
derive_param_tte(
  dataset_adsl = adsl,
  start_date = TRTSDT,
  event_conditions = list(ttae),
  censor_conditions = list(eot),
  source_datasets = list(adsl = adsl, ae = arrange(ae, desc(AESEQ))),
  set_values_to = exprs(
    PARAMCD = "TTAE"
  )
)
```
produces
```
# A tibble: 2 × 10
  USUBJID STUDYID EVENTDESC  SRCDOM SRCVAR  SRCSEQ  CNSR ADT        STARTDT    PARAMCD
  <chr>   <chr>   <chr>      <chr>  <chr>    <dbl> <int> <date>     <date>     <chr>  
1 01      AB42    AE         AE     AESTDTC      3     0 2021-01-03 2020-12-06 TTAE   
2 02      AB42    END OF TRT ADSL   TRTEDT      NA     1 2021-01-30 2021-01-16 TTAE   
```

### PR DESCRIPTION
**Pull request by ProfessorP-beep**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF and a PNG version of it to the same folder. (The PNG version can be created by taking a screenshot of the PDF version.)
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

File: R/derive_joined.R [hunk 1]
```diff
@@ -478,7 +478,7 @@ derive_vars_joined <- function(dataset,
     derive_var_obs_number(
       new_var = !!tmp_obs_nr,
       by_vars = by_vars_left,
-      check_type = "none"
+      "none"
```
[the remark this answers is not in the document]
Comment (ProfessorP-beep) [reply R/derive_joined.R:481]: I am not sure. Let me add it back in. I did a fresh pull before working on this again but I likely made a mistake

[the remark this answers is not in the document]
Comment (ProfessorP-beep) [reply R/derive_joined.R:481]: Its still there on my end

[the remark this answers is not in the document]
Comment (ProfessorP-beep) [reply R/derive_joined.R]: Reviewing to see if I made any other mistakes.

**Comment by bms63** [comment]
You need to fix this conflict.  You might need to accept the updated snapshot

File: tests/testthat/test-derive_param_tte.R [hunk 2]
```diff
@@ -640,7 +640,7 @@ test_that("derive_param_tte Test 9: errors if set_values_to contains invalid exp
       source_datasets = list(adsl = adsl, ae = ae),
       set_values_to = exprs(
         PARAMCD = paste0("TTAE", as.numeric(as.factor(AEDECOD))),
-        PARAM = past("Time to First", AEDECOD, "Adverse Event"),
+        PARAM = paste("Time to First", AEDECOD, "Adverse Event"),
```
Comment (bundfussr) [inline tests/testthat/test-derive_param_tte.R:643]: Please don't change this. The mistake is intentional to cause an error. Now the test is failing because the is no error anymore.

File: R/derive_param_tte.R [hunk 3]
```diff
@@ -386,6 +390,13 @@ derive_param_tte <- function(dataset = NULL,
   ) %>%
     mutate(!!tmp_event := 1L)
 
+  # check for duplicates in event_data
+  signal_duplicate_records(
+    dataset = event_data,
+    by_vars = expr_c(by_vars, subject_keys),
+    cnd_type = check_type
+  )
```
Comment (bundfussr) [inline R/derive_param_tte.R:398]: This check will never fail because `filter_date_sources()` returns at most one records per by group and subject. That's the reason why the test "derive_param_tte detects duplicates when check_type = 'warning'" fails.

File: tests/testthat/test-derive_param_tte.R [hunk 4]
```diff
@@ -928,3 +928,208 @@ test_that("list_tte_source_objects Test 14: expected objects produced", {
...
+    dataset_adsl = adsl,
+    start_date = TRTSDT,
+    event_conditions = list(ttae),
+    censor_conditions = list(eot),
+    source_datasets = list(adsl = adsl, ae = arrange(ae, desc(AESEQ))),
+    set_values_to = exprs(PARAMCD = "TTAE")
+  )
+
+  # Validate that the results are the same
+  expect_equal(result_sorted, result_unsorted, ignore_attr = TRUE)
```
Comment (bundfussr) [inline tests/testthat/test-derive_param_tte.R:1062]: Please use `expect_dfs_equal()` instead of `expect_equal()`. Then it is easier to see what the differences are.

It is not surprising that the test fails because you have added `order` to the source objects but it is not used in `filter_date_sources()`.

File: tests/testthat/test-derive_param_tte.R [hunk 5]
```diff
@@ -928,3 +928,208 @@ test_that("list_tte_source_objects Test 14: expected objects produced", {
...
+})
+
+# Test 17: "derive_param_tte produces expected output for common scenario"
+test_that("derive_param_tte produces expected output for common scenario", {
```
Comment (bundfussr) [inline tests/testthat/test-derive_param_tte.R:1066]: Is this test related to the code updates?

Comment (ProfessorP-beep) [reply tests/testthat/test-derive_param_tte.R:1066]: Yea, I was trying to write new tests for the code updates but let me know if this is wrong or unneeded.

File: tests/testthat/test-derive_param_tte.R (hunk 4 above)
Comment (ProfessorP-beep) [reply tests/testthat/test-derive_param_tte.R:1062]: Thanks, will make changes in couple hours.

File: tests/testthat/test-derive_param_tte.R (hunk 2 above)
Comment (ProfessorP-beep) [reply tests/testthat/test-derive_param_tte.R:643]: I see. I thought I had changed this by mistake. I'll change it back. Thanks.

File: tests/testthat/test-derive_param_tte.R (hunk 5 above)
Comment (bundfussr) [reply tests/testthat/test-derive_param_tte.R:1066]: I think "Test 17" is already covered by "Test 5". Or did I miss something?

File: tests/testthat/test-derive_param_tte.R [hunk 6]
```diff
@@ -928,3 +928,208 @@ test_that("list_tte_source_objects Test 14: expected objects produced", {
 
   expect_dfs_equal(expected_output, observed_output, keys = c("object"))
 })
+
+# Test 15: "derive_param_tte detects duplicates when check_type = 'warning'`
+test_that("derive_param_tte detects duplicates when check_type = 'warning'", {
```
Comment (bundfussr) [inline tests/testthat/test-derive_param_tte.R:933]: Please format as described in [Set up the Test Script](https://pharmaverse.github.io/admiraldev/dev/articles/unit_test_guidance.html#set-up-the-test-script).
You can do this easily with the addin from pharmaverse4devs (see [Addin `pharmaverse4devs::format_test_that_file()`](https://pharmaverse.github.io/admiraldev/dev/articles/unit_test_guidance.html#addin-pharmaverse4devsformat_test_that_file))

Comment (ProfessorP-beep) [reply tests/testthat/test-derive_param_tte.R:933]: Done. Double checking some changes and pushing

File: R/derive_param_tte.R (hunk 3 above)
Comment (ProfessorP-beep) [reply R/derive_param_tte.R:398]: I think I get it. I just made a push, but let me take a look.

Comment (ProfessorP-beep) [reply R/derive_param_tte.R:398]: Okay, let me know if this was effective. The error I was getting was that AEDECOD was not being included in the signal_duplicate_records function. So I bound dataset_adsl and source_datasets together then ran the check within derive_param_tte like so: 

#check for duplicates in dataset_adsl and source_datasets
  combined_dataset <- bind_rows(dataset_adsl, !!!source_datasets)

  signal_duplicate_records(
    dataset = combined_dataset,
    by_vars = expr_c(subject_keys, by_vars),
    cnd_type = check_type
  )

All the tests have passed now with some additional warnings. I have to run to some meetings and seminars today but am pushing now for review and can check back in the evening. On first glance not sure if the earlier tests should get a duplicate warning now as well.

File: tests/testthat/test-derive_param_tte.R [hunk 7]
```diff
@@ -974,3 +974,137 @@ test_that("list_tte_source_objects Test 15: expected objects produced", {
...
+
+  # Define event source with order
+  ttae <- event_source(
+    dataset_name = "ae",
+    date = AESTDT,
+    set_values_to = exprs(
+      EVENTDESC = "AE",
+      SRCDOM = "AE",
+      SRCVAR = "AESTDTC",
+      SRCSEQ = "AESEQ"
```
Comment (bundfussr) [inline tests/testthat/test-derive_param_tte.R:1070]:
```suggestion
      SRCSEQ = AESEQ
```
Otherwise, you don't see the difference.

At the moment there is a difference because `order` is not considered for the selection of the records.

File: R/derive_param_tte.R [hunk 8]
```diff
@@ -374,7 +378,17 @@ derive_param_tte <- function(dataset = NULL,
...
 
+ #check for duplicates in dataset_adsl and source_datasets
+  combined_dataset <- bind_rows(dataset_adsl, !!!source_datasets)
+
+  signal_duplicate_records(
+    dataset = combined_dataset,
+    by_vars = expr_c(subject_keys, by_vars),
+    cnd_type = check_type
+  )
+
```
Comment (bundfussr) [inline R/derive_param_tte.R:389]: This is not the right place for the check. Now both `derive_param_tte()` calls in "Test 16" produce a warning. But they shouldn't because `order` is specified there, which makes the selection unique.

I think you can pass `check_type` to `filter_date_sources()` and then pass it to the `filter_extreme()` call. Most likely you need to catch the duplicates message from `filter_extreme()` and rephrase it to make it helpful for the users.

**Review by bundfussr — CHANGES_REQUESTED** [review]

**Comment by ProfessorP-beep** [comment]
> You need to fix this conflict.  You might need to accept the updated snapshot

Hey @bms63 accepted the snapshots and passed the dev tools::check() on my end but it fails when pushed. I noticed in the failure output that the snapshots I accepted didn't seem to go through. Did I miss something?

**Review by bms63 — COMMENTED** [review]
It looks like a different test is falling over
image

File: R/derive_param_tte.R [hunk 9]
```diff
@@ -613,17 +622,31 @@ filter_date_sources <- function(sources,
...
+          filter_if(sources[[i]]$filter) %>%
+          arrange(!!!sources[[i]]$order) %>% # Ensure order is applied
+          filter_extreme(
+            order = exprs(!!source_date_var),
+            by_vars = expr_c(subject_keys, by_vars),
+            mode = mode,
+            check_type = check_type
+          )
+      },
+      warning = function(wrn) {
```
Comment (bundfussr) [inline R/derive_param_tte.R:638]: This catches warnings only. Errors and messages should be handled as well. (Maybe https://rlang.r-lib.org/reference/try_fetch.html is helpful.)

File: NEWS.md [hunk 10]
```diff
@@ -80,6 +80,15 @@ example, `">2.5 x ULN"` changed to `">2.5"` for grade 3. (#2534)
...
 # admiral 1.1.1
+
+- `check_type = "warning"` default argument added to `derive_param_tte` with an
+  `arg_match` function within the function so the user can use a valid input of 
+  `error, message, warning, or none`. `signal_duplicate_records()` has also been
+  added to the function on lines 394 and 411 to check for uniqueness of records. (#2481)
+  
+- `order()` function has been added to `event_source()` and `censor_source()` and
+  defaulted to `NULL` to allow sorting of input data. (#2481)
+
```
Comment (bundfussr) [inline NEWS.md:91]: This should be moved up to the "development version" section because admiral 1.1.1 is already released.

File: NEWS.md [hunk 11]
```diff
@@ -80,6 +80,15 @@ example, `">2.5 x ULN"` changed to `">2.5"` for grade 3. (#2534)
...
 
 # admiral 1.1.1
+
+- `check_type = "warning"` default argument added to `derive_param_tte` with an
+  `arg_match` function within the function so the user can use a valid input of 
+  `error, message, warning, or none`. `signal_duplicate_records()` has also been
+  added to the function on lines 394 and 411 to check for uniqueness of records. (#2481)
+  
+- `order()` function has been added to `event_source()` and `censor_source()` and
+  defaulted to `NULL` to allow sorting of input data. (#2481)
```
Comment (bundfussr) [inline NEWS.md:90]:
```suggestion
- `order` argument has been added to `event_source()` and `censor_source()` and
  defaulted to `NULL` to allow specifying variables in addition to the date variable. 
  This can be used to ensure the uniqueness of the select records if there is more
  than one record per date.  (#2481)
```

File: NEWS.md [hunk 12]
```diff
@@ -80,6 +80,15 @@ example, `">2.5 x ULN"` changed to `">2.5"` for grade 3. (#2534)
 </details>
 
 # admiral 1.1.1
+
+- `check_type = "warning"` default argument added to `derive_param_tte` with an
+  `arg_match` function within the function so the user can use a valid input of 
+  `error, message, warning, or none`. `signal_duplicate_records()` has also been
+  added to the function on lines 394 and 411 to check for uniqueness of records. (#2481)
```
Comment (bundfussr) [inline NEWS.md:87]: Could you rephrase this item such that it describes how the change affects the users? No need to add details for developers.

File: R/derive_param_tte.R [hunk 13]
```diff
@@ -322,7 +322,11 @@ derive_param_tte <- function(dataset = NULL,
                              censor_conditions,
                              create_datetime = FALSE,
                              set_values_to,
-                             subject_keys = get_admiral_option("subject_keys")) {
+                             subject_keys = get_admiral_option("subject_keys"),
+                             check_type = "warning") {
+  # Match check_type to valid admiral options
+  check_type <- rlang::arg_match(check_type, c("warning", "message", "error", "none"))
```
Comment (bundfussr) [inline R/derive_param_tte.R:328]: Please use the admiraldev assertions (`assert_character_scalar()`) and move it to the "checking and quoting" section below.

**Review by bundfussr — CHANGES_REQUESTED** [review]

File: R/derive_param_tte.R [hunk 14]
```diff
@@ -613,17 +642,50 @@ filter_date_sources <- function(sources,
...
+          "i Consider reviewing your `by_vars` or `order` argument to ensure uniqueness."
+        ))
+      },
+      message = function(msg) {
+        cli::cli_inform(c(
+          "Processing dataset '{.val {sources[[i]]$dataset_name}}'...",
+          "i Filter and order criteria: {.val {paste(c(subject_keys, by_vars,
+          sources[[i]]$order), collapse = ', ')}}."
+        ))
+      }
```
Comment (bundfussr) [inline R/derive_param_tte.R:686]: Once https://github.com/pharmaverse/admiral/pull/2592 is merged this could be simplified:
```
      duplicate_records = function(cnd) {
        cnd_funs <- list(message = cli_inform, warning = cli_warn, error = cli_abort)
        cnd_funs[[check_type]](
          paste(
            "Dataset {.val {sources[[i]]$dataset_name}} contains duplicate records with respect to",
            "{.var {cnd$by_vars}}"
          ),
          class = class(cnd))
        cnd_muffle(cnd)
        zap()
      }
```

File: tests/testthat/test-derive_param_tte.R [hunk 15]
```diff
@@ -974,3 +974,129 @@ test_that("list_tte_source_objects Test 15: expected objects produced", {
 
   expect_dfs_equal(expected_output, observed_output, keys = c("object"))
 })
+
+## Test 15: derive_param_tte detects duplicates when check_type = 'warning' ----
```
Comment (bundfussr) [inline tests/testthat/test-derive_param_tte.R:978]: Please move the new tests before "Test 14". ("Test 14" and "Test 15" test `list_tte_source_objects()` and not `derive_param_tte()`). Then all tests for `derive_param_tte()` are in the same section.

**Comment by rossfarrugia** [comment]
@ProfessorP-beep how's it going with the review updates for this one? I only ask as it impacts updates for our internal admiralroche package that I am assigned to. Hoping this one could merge before the holidays and then I could take care of mine early Jan.

File: vignettes/bds_tte.Rmd [hunk 16]
```diff
@@ -37,6 +37,7 @@ The examples of this vignette require the following packages.
 library(admiral)
 library(dplyr, warn.conflicts = FALSE)
 library(pharmaversesdtm)
+library(rlang)
```
[the remark this answers is not in the document]
Comment (ProfessorP-beep) [reply vignettes/bds_tte.Rmd:40]: When I was running devtools::check() I kept getting an error where it couldn't find 'try_catch()'. This seemed to get it working despite it already being loaded.

[the remark this answers is not in the document]
Comment (bundfussr) [reply vignettes/bds_tte.Rmd:40]: I tried it without the new line and it worked for me. So I assume it is no longer needed.

[the remark this answers is not in the document]
Comment (ProfessorP-beep) [reply vignettes/bds_tte.Rmd:40]: Nice, I'll remove it from this list.

**Comment by ProfessorP-beep** [comment]
> @ProfessorP-beep how's it going with the review updates for this one? I only ask as it impacts updates for our internal admiralroche package that I am assigned to. Hoping this one could merge before the holidays and then I could take care of mine early Jan.

Sorry, making these changes this afternoon.

File: R/derive_param_tte.R [hunk 17]
```diff
@@ -60,6 +60,14 @@
 #'
 #'   A list of symbols created using `exprs()` is expected.
 #'
+#' @param check_type Check uniqueness
+#'
+#'   If `"warning"`, `"message"`, or `"error"` is specified, the specified message is issued
+#'   if the observations of the input dataset are not unique with respect to the
+#'   by variables and the order.
+#'
+#'  Default: `"none"`
```
Comment (rossfarrugia) [inline R/derive_param_tte.R:69]: @ProfessorP-beep I would add an extra example to the `derive_param_tte()` documentation to show a case where sorting by order is useful, e.g. time to first serious AE and have a test case where one patient has 2 serious AEs on same date and you need to sort additionally by AESEQ.

File: tests/testthat/test-derive_param_tte.R [hunk 18]
```diff
@@ -932,17 +932,143 @@ test_that("derive_param_tte Test 13: error if dataset_name not in source_datsets
...
+      censor_conditions = list(eot),
+      source_datasets = list(adsl = adsl, ae = ae),
+      set_values_to = exprs(PARAMCD = "TTAE"),
+      check_type = "warning"
+    ),
+    regexp = "Dataset '.*' contains duplicate records."
+  )
+})
+
+## Test 15: derive_param_tte produces consistent results regardless of input sort order ----
```
Comment (rossfarrugia) [inline tests/testthat/test-derive_param_tte.R:993]: @ProfessorP-beep I would also add an extra unit test to check that the new `order` argument works here to see that the user can change the sort order used for both events and censors. You could use the same example as in my other suggestion but make the input data sorted descending by AESEQ so that you're sure the argument works to then correctly sort the same date AEs additionally by AESEQ.

File: R/derive_param_tte.R [hunk 19]
```diff
@@ -782,6 +843,10 @@ extend_source_datasets <- function(source_datasets,
 #'   SRCDOM = "ADSL", SRCVAR = "DTHDT")`. The values must be a symbol, a
 #'   character string, a numeric value, an expression, or `NA`.
 #'
+#' @param order Sort order
+#'
+#'   If the argument is set to a non-null value, for each by group the first or
+#'   last observation
```
Comment (rossfarrugia) [inline R/derive_param_tte.R:849]: @ProfessorP-beep from a user perspective i find this argument description confusing. I'm unclear whether i need to use `exprs()` like for `set_values_to` explained above and i don't really understand the description here. I thought it would be worded more something like:

A named list returned by `exprs()` defining optional additional variables that the input dataset is sorted on after `date`.

Comment (rossfarrugia) [reply R/derive_param_tte.R:849]: @bundfussr any thoughts on this suggestion? just in case i'm missing anything.

Comment (bundfussr) [reply R/derive_param_tte.R:849]: @rossfarrugia , I agree that the description should be updated. I would move the technical details to "Permitted Values". For example
> Additional variables that the source dataset is sorted on after `date`.
>
> *Permitted Values*: list of variables created by `exprs()` e.g. `exprs(ASEQ)`

File: tests/testthat/test-derive_param_tte.R (hunk 18 above)
Comment (ProfessorP-beep) [reply tests/testthat/test-derive_param_tte.R:993]: Gotcha, will make the additions in the morning.

File: R/derive_param_tte.R [hunk 20]
```diff
@@ -321,6 +321,50 @@
...
+#' adsl <- tribble(
+#'   ~USUBJID, ~TRTSDT, ~EOSDT,
+#'   "01", ymd("2020-12-06"), ymd("2021-03-06"),
+#'   "02", ymd("2021-01-16"), ymd("2021-02-03")
+#' ) %>% mutate(STUDYID = "AB42")
+#'
+#' ae <- tribble(
+#'   ~USUBJID, ~AESTDTC, ~AESEQ, ~AESER, ~AEDECOD,
+#'   "01", "2021-01-03", 1, "Y", "Flu",
+#'   "01", "2021-01-03", 2, "Y", "cough",
```
Comment (rossfarrugia) [inline R/derive_param_tte.R:335]:
```suggestion
#'   "01", "2021-01-03", 2, "Y", "Cough",
```
for consistency with other rows

File: R/derive_param_tte.R [hunk 21]
```diff
@@ -321,6 +321,50 @@
...
+#'   source_datasets = list(adsl = adsl, ae = ae),
+#'   event_conditions = list(event_source(
+#'     dataset_name = "ae",
+#'     date = AESTDT,
+#'     set_values_to = exprs(
+#'       EVENTDESC = "Serious AE",
+#'       SRCSEQ = AESEQ
+#'     ),
+#'     filter = AESER == "Y",
+#'     order = exprs(AESTDT, AESEQ)
```
Comment (rossfarrugia) [inline R/derive_param_tte.R:354]: do we need to include `AESTDT` here? I assumed this would always first sort on whatever you pass into the `date` argument and then the `order` variable(s) would be additionally added to the sort order after this?

File: R/derive_param_tte.R [hunk 22]
```diff
@@ -845,8 +889,10 @@ extend_source_datasets <- function(source_datasets,
 #'
 #' @param order Sort order
 #'
-#'   If the argument is set to a non-null value, for each by group the first or
-#'   last observation
+#'   An optional named list returned by `exprs()` defining additional variables
+#'   that the input dataset is sorted on after `date`.
+#'
+#'   Permitted Values: list of variables created by `exprs()` e.g. `exprs(ASEQ)`.
```
Comment (rossfarrugia) [inline R/derive_param_tte.R:895]:
```suggestion
#'   *Permitted Values:* list of variables created by `exprs()` e.g. `exprs(ASEQ)`.
```

File: R/derive_param_tte.R [hunk 23]
```diff
@@ -845,8 +889,10 @@ extend_source_datasets <- function(source_datasets,
 #'
 #' @param order Sort order
 #'
-#'   If the argument is set to a non-null value, for each by group the first or
-#'   last observation
+#'   An optional named list returned by `exprs()` defining additional variables
+#'   that the input dataset is sorted on after `date`.
```
Comment (rossfarrugia) [inline R/derive_param_tte.R:893]:
```suggestion
#'   that the source dataset is sorted on after `date`.
```
Stefan used "source" and it is more in keeping with the argument naming, rather than my suggested "input"

File: tests/testthat/_snaps/derive_param_tte.md [hunk 24]
```diff
@@ -61,7 +61,7 @@
       i Following names were provided by `source_datasets`: "adsl"
       i But, `censor_conditions[[1]]$dataset_name = adls`
 
-# list_tte_source_objects Test 14: error is issued if package does not exist
+# list_tte_source_objects Test 16: error is issued if package does not exist
```
Comment (rossfarrugia) [inline tests/testthat/_snaps/derive_param_tte.md:64]: I think this should be 17

File: tests/testthat/test-derive_param_tte.R [hunk 25]
```diff
@@ -990,8 +990,68 @@ test_that("derive_param_tte Test 14: detects duplicates in input datasets via pi
...
+    start_date = TRTSDT,
+    event_conditions = list(event_source(
+      dataset_name = "ae",
+      date = AESTDT,
+      set_values_to = exprs(
+        EVENTDESC = "Serious AE",
+        SRCSEQ = AESEQ
+      ),
+      filter = AESER == "Y",
+      order = exprs(AESTDT, AESEQ) # Should re-sort so that AESEQ=1 (Flu) is chosen on tie
```
Comment (rossfarrugia) [inline tests/testthat/test-derive_param_tte.R:1028]: Same comment as above

**Review by rossfarrugia — CHANGES_REQUESTED** [review]
@ProfessorP-beep thanks for updating for my comments! i spotted a few minor things in the updates

File: R/derive_param_tte.R [hunk 26]
```diff
@@ -529,7 +600,7 @@ derive_param_tte <- function(dataset = NULL,
 #' @return A dataset with one observation per subject as described in the
 #'   "Details" section.
 #'
-#' @noRd
+#' @keywords internal
```
Comment (rossfarrugia) [inline R/derive_param_tte.R:603]: this update is causing the R CMD check fail in the CI - not sure if it was needed or what the rationale for updating it was? Maybe @bundfussr could comment

Comment (bundfussr) [reply R/derive_param_tte.R:603]: @rossfarrugia , this was changed to create the documentation for the function. Before no help or html page was created.

@ProfessorP-beep , as the function is not exported, you need to prefix it in the example with `admiral:::`.

File: tests/testthat/_snaps/derive_param_tte.md (hunk 24 above)
Comment (rossfarrugia) [reply tests/testthat/_snaps/derive_param_tte.md:64]: @ProfessorP-beep from my small review comments only this one still needs updating, and looks like you need to merge latest `main` branch into this one. I would recommend @bundfussr takes another look and is the approver of this PR before we merge in the updates as i only did some minor checks around the documentation and tests.

File: R/derive_param_tte.R [hunk 27]
```diff
@@ -505,6 +566,16 @@ derive_param_tte <- function(dataset = NULL,
 #'
 #'   Permitted Values:  `"first"`, `"last"`
 #'
+#'  @param check_type Check uniqueness
+#'
+#'   If `"warning"`, `"message"`, or `"error"` is specified, the specified message is issued
+#'   if the observations of the input dataset are not unique with respect to the
+#'   by variables and the order.
```
Comment (bundfussr) [inline R/derive_param_tte.R:573]:
```suggestion
#'   if the observations of the source datasets are not unique with respect to the
#'   by variables and the date and order specified in the `tte_source()` objects.
```

File: R/derive_param_tte.R [hunk 28]
```diff
@@ -505,6 +566,16 @@ derive_param_tte <- function(dataset = NULL,
...
+#'
+#'  Default: `"none"`
+#'
```
Comment (bundfussr) [inline R/derive_param_tte.R:576]:
```suggestion
```

File: R/derive_param_tte.R [hunk 29]
```diff
@@ -505,6 +566,16 @@ derive_param_tte <- function(dataset = NULL,
 #'
 #'   Permitted Values:  `"first"`, `"last"`
 #'
+#'  @param check_type Check uniqueness
```
Comment (bundfussr) [inline R/derive_param_tte.R:569]:
```suggestion
#' @param check_type Check uniqueness
```
(If the tag is indented, it is rendered as text.)

File: inst/WORDLIST [hunk 30]
```diff
@@ -304,6 +304,7 @@ msec
 nd
 occds
 onwards
+param
```
Comment (bundfussr) [inline inst/WORDLIST:307]: I think this is not necessary. You can check by calling `spelling::update_wordlist()`.

File: tests/testthat/test-derive_param_tte.R [hunk 31]
```diff
@@ -932,17 +932,203 @@ test_that("derive_param_tte Test 13: error if dataset_name not in source_datsets
...
+    censor = 1,
+    set_values_to = exprs(
+      EVENTDESC = "END OF TRT",
+      SRCDOM = "ADSL",
+      SRCVAR = "TRTEDT"
+    )
+  )
+
+  # Run derive_param_tte and check for warning
+  expect_warning(
```
Comment (bundfussr) [inline tests/testthat/test-derive_param_tte.R:979]: `expect_snapshot()` should be used because the message is created by the function which is tested. This ensures that the complete message looks as intended.

File: tests/testthat/test-derive_param_tte.R [hunk 32]
```diff
@@ -932,17 +932,203 @@ test_that("derive_param_tte Test 13: error if dataset_name not in source_datsets
...
+  # Define AE dataset with duplicates
+  ae <- tibble::tribble(
+    ~USUBJID, ~AESTDTC,     ~AESEQ, ~AEDECOD,
+    "01",     "2021-01-03",      1, "Flu",
+    "01",     "2021-03-04",      2, "Cough",
+    "01",     "2021-01-03",      3, "Flu"
+  ) %>% mutate(STUDYID = "AB42", AESTDT = ymd(AESTDTC))
+
+  # Deduplicate AE dataset to remove duplicate warnings
+  ae <- ae %>% distinct(STUDYID, USUBJID, AESTDT, .keep_all = TRUE)
```
Comment (bundfussr) [inline tests/testthat/test-derive_param_tte.R:1071]: Why are the duplicates (with respect to the date) removed?

I think without the duplicates the test doesn't make sense because the results were affected by the sort order only when duplicates occurred. Or did I miss something?

**Review by bundfussr — CHANGES_REQUESTED** [review]

File: inst/WORDLIST (hunk 30 above)
Comment (ProfessorP-beep) [reply inst/WORDLIST:307]: Done. Will push soon.

**Comment by bms63** [comment]
Hi @ProfessorP-beep are we on track with updates to be completed by EOD Friday.  We need to give @bundfussr some time for final review.   Many thanks for tackling this update!!

File: R/derive_param_tte.R [hunk 33]
```diff
@@ -262,10 +270,10 @@
...
 #'
 #' ae <- tribble(
-#'   ~USUBJID, ~AESTDTC,           ~AESEQ, ~AEDECOD,
-#'   "01",     "2021-01-03T10:56", 1,      "Flu",
-#'   "01",     "2021-03-04",       2,      "Cough",
-#'   "01",     "2021",             3,      "Flu"
+#'   ~USUBJID, ~AESTDTC, ~AESEQ, ~AEDECOD,
+#'   "01", "2021-01-03T10:56", 1, "Flu",
+#'   "01", "2021-03-04", 2, "Cough",
+#'   "01", "2021-", 3, "Flu"
```
[the remark this answers is not in the document]
Comment (ProfessorP-beep) [reply R/derive_param_tte.R:276]: I'm unsure how this happened. I'm reverting it back.

File: tests/testthat/_snaps/derive_param_tte.md (hunk 24 above)
Comment (rossfarrugia) [reply tests/testthat/_snaps/derive_param_tte.md]: thanks for resolving this last comment Phil!

**Comment by ProfessorP-beep** [comment]
> Hi @ProfessorP-beep are we on track with updates to be completed by EOD Friday. We need to give @bundfussr some time for final review. Many thanks for tackling this update!!

Yea, we should be good. I'm just going to fix the errors from this last push.

File: NEWS.md [hunk 34]
```diff
@@ -14,6 +14,8 @@ target range. (#2571)
 - Update `ADEG` template to flag `ABLFL` and `ANL01FL` based on `DTYPE == "AVERAGE"` records. (#2561)
 
 ## Updates of Existing Functions
+- added `"message"` as option for `check_type` argument in `derive_var_obs_number` function. (#2481)
```
Comment (bms63) [inline NEWS.md:17]:
```suggestion
- added `"message"` as option for `check_type` argument in `derive_var_obs_number()` function. (#2481)
```

**Comment by bms63** [comment]
> @bms63 sorry that request was an accident. I meant to request review from @bundfussr

all good! i made a suggestion in the news!  

Can you hide comments where the issue was addressed?
image

Also good just to hide all the comments discussion so we can see if anything needs to finalized.

**Review by bundfussr — APPROVED** [review]
@ProfessorP-beep , thanks for your great work and your patience!

I think this PR is ready to merge. (I only did some cosmetic updates.)
