### PR TITLE
Closes #2729 optional_order: Make order argument in derive_var_joined_exist_flag() optional (and doc enhanements for `filter_joined()`, `derive_var_joined_exist_flag()`)

### LINKED ISSUE #2729: Bug: warning unexpectedly issued in `derive_var_joined_exist_flag()` when no order is passed
### What happened?

I wanted to create a flag in `AE` which flagged an `AE` record if and only if there existed an intraocular inflammation record for that patient in `OE` such that `AEGRPID = OEGRPID`. I though of achieving this with a call to `derive_var_joined_exist_flag()`:
```
derive_var_joined_exist_flag(
  dataset = ae,
  dataset_add = oe,
  by_vars =  exprs(USUBJID),
  new_var = AEIOIFL,
  join_type = "all",
  join_vars = exprs(OECAT, OEGRPID),
  order = exprs(),
  filter_join = OECAT == "ADVERSE EVENTS-INTRAOCULAR INFLAMMATION" & OEGRPID == AEGRPID
)
```
I don't think there is anything to pass to the order argument. But a call such as this will throw a warning if we have more than one AE in each by group (see below). @bundfussr and I think it is a bug or at least unexpected behaviour.

### Session Information

R version 4.3.3 (2024-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] admiral_1.2.0.9022 testthat_3.2.1.1  

loaded via a namespace (and not attached):
 [1] tidyr_1.3.1           utf8_1.2.4            generics_0.1.3        xml2_1.3.6           
 [5] stringi_1.8.3         hms_1.1.3             digest_0.6.35         magrittr_2.0.3       
 [9] timechange_0.3.0      pkgload_1.4.0.9000    fastmap_1.1.1         rprojroot_2.0.4      
[13] pkgbuild_1.4.4        sessioninfo_1.2.2     brio_1.1.4            urlchecker_1.0.1     
[17] promises_1.3.0        admiraldev_1.2.0.9005 purrr_1.0.2           fansi_1.0.6          
[21] cli_3.6.2             shiny_1.8.1.1         rlang_1.1.6.9000      ellipsis_0.3.2       
[25] withr_3.0.0           remotes_2.5.0         cachem_1.0.8          devtools_2.4.5       
[29] tools_4.3.3           memoise_2.0.1         dplyr_1.1.4           httpuv_1.6.15        
[33] vctrs_0.6.5           R6_2.5.1              mime_0.12             lifecycle_1.0.4      
[37] lubridate_1.9.3       stringr_1.5.1         fs_1.6.3              htmlwidgets_1.6.4    
[41] usethis_2.2.3         miniUI_0.1.1.1        pkgconfig_2.0.3       desc_1.4.3           
[45] pillar_1.9.0          later_1.3.2           glue_1.7.0            profvis_0.3.8        
[49] Rcpp_1.0.12           xfun_0.43             tibble_3.2.1          tidyselect_1.2.1     
[53] knitr_1.46            rstudioapi_0.16.0     xtable_1.8-4          htmltools_0.5.8.9000 
[57] compiler_4.3.3        roxygen2_7.3.2       

### Reproducible Example

```
library(tibble)
library(dplyr)
library(admiral)

ae <- tibble::tribble(
  ~USUBJID, ~AEGRPID, ~AEDECOD,
  "1", "001", "IRITIS",
  "2", "003", "FATIGUE",
  "2", "007", "INFLAMMATION",
  "3", "002", "HEADACHE",
  "4", "001", "CARDIAC ARREST"
)

oe <- tibble::tribble(
  ~USUBJID, ~OEGRPID, ~OECAT,
  "1", "001", "ADVERSE EVENTS-INTRAOCULAR INFLAMMATION",
  "2", "003", "OPHTHALMIC IMAGING",
  "2", "007", "ADVERSE EVENTS-INTRAOCULAR INFLAMMATION",
  "3", "009", "OPHTHALMIC IMAGING",
  "3", "001", "OPHTHALMIC IMAGING"
)

derive_var_joined_exist_flag(
  dataset = ae,
  dataset_add = oe,
  by_vars =  exprs(USUBJID),
  new_var = AEIOIFL,
  join_type = "all",
  join_vars = exprs(OECAT, OEGRPID),
  order = exprs(),
  filter_join = OECAT == "ADVERSE EVENTS-INTRAOCULAR INFLAMMATION" & OEGRPID == AEGRPID
)
```
Works:
```
# A tibble: 5 × 4
  USUBJID AEGRPID AEDECOD        AEIOIFL
  <chr>   <chr>   <chr>          <chr>  
1 1       001     IRITIS         Y      
2 2       003     FATIGUE        NA     
3 2       007     INFLAMMATION   Y      
4 3       002     HEADACHE       NA     
5 4       001     CARDIAC ARREST NA  
```
but produces warning due to two AEs for patient 2:
```
Warning messages:
1: Dataset contains duplicate records with respect to `USUBJID`
ℹ Run admiral::get_duplicates_dataset() to access the duplicate records 
2: Dataset contains duplicate records with respect to `USUBJID`
ℹ Run admiral::get_duplicates_dataset() to access the duplicate records 
> admiral::get_duplicates_dataset()
Duplicate records with respect to `USUBJID`.
# A tibble: 2 × 5
  USUBJID AEGRPID AEDECOD      tmp_obs_nr__1 tmp_obs_nr_left_1
* <chr>   <chr>   <chr>                <int>             <int>
1 2       003     FATIGUE                  2                 1
2 2       007     INFLAMMATION             3                 2
```
Note: as @bundfussr helpfully pointed out, in this specific case, `derive_var_merged_exist_flag()` could be used instead and doesn't throw a warning.
```
derive_var_merged_exist_flag(
  dataset = ae,
  dataset_add = oe,
  by_vars = exprs(USUBJID, AEGRPID = OEGRPID),
  condition = OECAT == "ADVERSE EVENTS-INTRAOCULAR INFLAMMATION",
  new_var = AEIOIFL
)
```

### PR DESCRIPTION
**Pull request by bundfussr**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/cran-release/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF and a PNG version of it to the same folder. (The PNG version can be created by taking a screenshot of the PDF version.)
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

File: R/derive_var_joined_exist_flag.R [hunk 1]
```diff
@@ -206,7 +208,7 @@
 #'   fulfilling the condition is included). If for an observation of the input
 #'   dataset the condition is not fulfilled, the observation is removed.
 #'
-#'   For an example see the last example in the "Examples" section.
+#'   For examples the "Examples" section.
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R]:
```suggestion
#'   For examples see the "Examples" section.
```

Comment (manciniedoardo) [reply R/derive_var_joined_exist_flag.R]: Also missing a full stop at the end of Step 5.

File: R/derive_var_joined_exist_flag.R [hunk 2]
```diff
@@ -235,11 +237,17 @@
 #'
 #' @export
 #'
-#' @examples
+#' @examplesx
+#' @caption Flag records considering other records (`filter_join`, `join_vars`)
+#' @info In this example, records with a duration longer than 30 and on or after
+#'   7 days before a COVID AE (`ACOVFL == "Y"`) should be flagged. The condition
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R]:
```suggestion
#' @info In this example, records with a duration longer than 30 and which are followed 
#'   by a COVID AE (`ACOVFL == "Y"`) at least seven days later should be flagged. The condition
```

Comment (manciniedoardo) [reply R/derive_var_joined_exist_flag.R]: I think it'd be good to explain why `join_type = "all"` here, as naively one may think `join_type = "after"` could work.

File: R/derive_var_joined_exist_flag.R [hunk 3]
```diff
@@ -261,11 +269,14 @@
...
 #'   join_type = "all",
-#'   order = exprs(ADY),
 #'   filter_join = ADURN > 30 & ACOVFL.join == "Y" & ADY >= ADY.join - 7
 #' )
 #'
-#' # flag observations with AVALC == "Y" and AVALC == "Y" at one subsequent visit
+#' @caption Considering only records after the current on (`join_type = "after"`)
+#' @info In this example, records with `AVALC == "Y"` and `AVALC == "Y"` at a
+#'   subsequent visit should be flagged. `join_type = "after"` is specified to
+#'   consider only records after the current one.
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R]: I'd explain here why now `order` needs to be specified.

File: R/derive_var_joined_exist_flag.R [hunk 4]
```diff
@@ -287,11 +298,21 @@
...
 #'   join_type = "after",
 #'   order = exprs(AVISITN),
-#'   filter_join = AVALC == "Y" & AVALC.join == "Y" & AVISITN < AVISITN.join
+#'   filter_join = AVALC == "Y" & AVALC.join == "Y"
 #' )
 #'
-#' # select observations with AVALC == "CR", AVALC == "CR" at a subsequent visit,
-#' # only "CR" or "NE" in between, and at most one "NE" in between
+#' @caption Considering only records up to a condition (`first_cond_upper`)
+#' @info In this example, the records with
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R]: Could add a sentence here giving some context to where this example is coming from? Ie some sort of confirmed response in oncology? Just thinking that this would the be indexed in our search index and could be surfaced if someone is looking for how to derive this endpoint.

File: R/derive_var_joined_exist_flag.R [hunk 5]
```diff
@@ -323,9 +344,19 @@
 #'     count_vals(var = AVALC.join, val = "NE") <= 1
 #' )
 #'
-#' # flag observations with AVALC == "PR", AVALC == "CR" or AVALC == "PR"
-#' # at a subsequent visit at least 20 days later, only "CR", "PR", or "NE"
-#' # in between, at most one "NE" in between, and "CR" is not followed by "PR"
+#' @caption Considering order of values (`min_cond()`, `max_cond()`)
+#' @info In this example, records with
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R]: Similar comment here about giving context for the endpoint.

File: R/derive_var_joined_exist_flag.R [hunk 6]
```diff
@@ -323,9 +344,19 @@
...
+#' - `AVALC == "PR"`,
+#' - `AVALC == "CR"` or `AVALC == "PR"` at a subsequent visit at least 20 days later,
+#' - only `"CR"`, `"PR"`, or `"NE"` in between,
+#' - at most one `"NE"` in between, and
+#' - `"CR"` is
+#'   not followed by `"PR"`
+#'
+#' should be flagged. The last condition is realized by using `min_cond()` and
+#' `max_cond()`, ensuring that the first occurrence of `"CR"` is after the last
+#' occurrence of `"PR"`.
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R]: I would explain what the second `count_vals` is doing, ie accounting for the case that there are no `CR`s in between?

File: R/derive_var_joined_exist_flag.R [hunk 7]
```diff
@@ -363,7 +394,13 @@
 #'     )
 #' )
 #'
-#' # flag observations with CRIT1FL == "Y" at two consecutive visits or at the last visit
+#' @caption Considering the order of records (`tmp_obs_nr_var`)
+#' @info In this example, the records with `CRIT1FL == "Y"` at two consecutive
+#' visits or at the last visit should be flagged. A temporary order variable is
+#' created by specifying the `tmp_obs_nr_var` argument. It is used in
+#' `filter_join` then. The temporary variable doesn't need to be specified for
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R]:
```suggestion
#' created by specifying the `tmp_obs_nr_var` argument. Then t is used in
#' `filter_join`. The temporary variable doesn't need to be specified for
```

File: R/derive_var_joined_exist_flag.R [hunk 8]
```diff
@@ -391,7 +428,9 @@
 #'     (tmp_obs_nr + 1 == tmp_obs_nr.join | tmp_obs_nr == max(tmp_obs_nr.join))
 #' )
 #'
-#' # first_cond_lower and first_cond_upper argument
+#' @caption Considering a range of records only (`first_cond_lower`, `first_cond_upper`)
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R]: I think this is a simpler example than some of the oncology ones. I'm kind of torn, but wondering if this should go further up? What do you think?

File: R/derive_var_joined_exist_flag.R [hunk 9]
```diff
@@ -436,16 +479,17 @@
 #'   filter_join = val == "0" & all(val.join %in% c("+", "++"))
 #' )
 #'
-#' # flag each dose which is lower than the previous dose per subject
+#' @caption Flag each dose which is lower than the previous dose per subject
+#' @code
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R:498]: I think this one would be better placed as another `tmp_obs_nr` example?

File: R/derive_var_joined_exist_flag.R [hunk 10]
```diff
@@ -482,15 +530,14 @@
 #'   dataset_add = adqs,
 #'   new_var = DDETERFL,
 #'   by_vars = exprs(USUBJID, PARAMCD),
-#'   join_vars = exprs(CHGCAT1),
+#'   join_vars = exprs(CHGCAT1, ADY),
 #'   join_type = "all",
-#'   order = exprs(ADY),
 #'   filter_join = all(CHGCAT1.join == "Worsened" | ADY > ADY.join)
 #' )
```
Comment (manciniedoardo) [inline R/derive_var_joined_exist_flag.R:551]: I'd add a section similar to [this one](https://pharmaverse.github.io/admiral/dev/reference/derive_vars_joined.html#further-examples) explaining where to find examples for `true_value`, `false_value` and `missing_value` as you haven't included them here - otherwise maybe you could try interspersing them among some of the simpler examples?

Comment (manciniedoardo) [reply R/derive_var_joined_exist_flag.R:551]: Also for `check_type` - is it worth adding a very short example where this is suppressed? After all this is why the whole issue arose... Conscious though that this is already getting quite long!

File: R/filter_joined.R [hunk 11]
```diff
@@ -221,13 +241,17 @@
 #'
 #' @export
 #'
-#' @examples
-#'
+#' @examplesx
+#' @caption Filter records considering other records (`filter_join`, `join_vars`)
+#' @info In this example, the input dataset should be restricted to records with
+#'   a duration longer than 30 and on or after 7 days before a COVID AE (`ACOVFL
+#'   == "Y"`). The condition for restricting the records is specified by the
```
Comment (manciniedoardo) [inline R/filter_joined.R]:
```suggestion
#'   a duration longer than 30 and which are followed by a COVID AE (`ACOVFL == "Y"`) at
#'   least seven days later should be filtered. The condition for restricting the records 
#'   is specified by the
```

File: R/filter_joined.R [hunk 12]
```diff
@@ -248,11 +272,14 @@
 #'   by_vars = exprs(USUBJID),
 #'   join_vars = exprs(ACOVFL, ADY),
 #'   join_type = "all",
-#'   order = exprs(ADY),
 #'   filter_join = ADURN > 30 & ACOVFL.join == "Y" & ADY >= ADY.join - 7
 #' )
 #'
-#' # filter observations with AVALC == "Y" and AVALC == "Y" at a subsequent visit
+#' @caption Considering only records after the current on (`join_type = "after"`)
```
Comment (manciniedoardo) [inline R/filter_joined.R]:
```suggestion
#' @caption Considering only records after the current one (`join_type = "after"`)
```

File: R/filter_joined.R [hunk 13]
```diff
@@ -248,11 +272,14 @@
...
+#' @info In this example, the input dataset is restricted to records with `AVALC
+#'   == "Y"` and `AVALC == "Y"` at a subsequent visit. `join_type = "after"` is
+#'   specified to consider only records after the current one.
```
Comment (manciniedoardo) [inline R/filter_joined.R]: Explain why `order` is needed here too

File: R/derive_var_joined_exist_flag.R (hunk 1 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: Updated

File: R/derive_var_joined_exist_flag.R (hunk 2 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: I've explained the reason for `join_type = "all"`.

I think your suggested change is not correct. I've rephrased it. What do you think?

File: R/derive_var_joined_exist_flag.R (hunk 3 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: Done

File: R/derive_var_joined_exist_flag.R (hunk 4 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: I've added the context. Do you think it is sufficient?

File: R/derive_var_joined_exist_flag.R (hunk 5 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: Done

File: R/derive_var_joined_exist_flag.R (hunk 6 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: Done

File: R/derive_var_joined_exist_flag.R (hunk 7 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: Updated

File: R/derive_var_joined_exist_flag.R (hunk 8 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: I was considering this, too. I've moved it up.

File: R/derive_var_joined_exist_flag.R (hunk 9 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R:498]: Caption updated.

File: R/derive_var_joined_exist_flag.R (hunk 10 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R:551]: I've included `true_value` and `false_value` in the second example. (`missing_value` is not provided by the function.)

I've also added an example for `check_type`. Please let me know what you think.

File: R/filter_joined.R (hunk 11 above)
Comment (bundfussr) [reply R/filter_joined.R]: See my comment for `derive_var_joined_exist_flag()` above.

File: R/filter_joined.R (hunk 12 above)
Comment (bundfussr) [reply R/filter_joined.R]: Updated

File: R/filter_joined.R (hunk 13 above)
Comment (bundfussr) [reply R/filter_joined.R]: Updated

I've also updated `filter_joined()` according to your comments on `derive_var_joined_exist_flag()`.

File: R/derive_var_joined_exist_flag.R (hunk 2 above)
Comment (manciniedoardo) [reply R/derive_var_joined_exist_flag.R]: You're right - what about "up to seven days before"?

Comment (manciniedoardo) [reply R/derive_var_joined_exist_flag.R]: I also think it still needs a little more clarification because users may think that `join_type = "after"` could be used since you only need to look after the current record to check for a COVID AE. So you'd need to explain where the before records are needed. Trying to put myself in a user's mindset as i too struggled with this previously.

File: R/derive_var_joined_exist_flag.R (hunk 10 above)
Comment (manciniedoardo) [reply R/derive_var_joined_exist_flag.R:551]: looks good thanks!

File: R/filter_joined.R (hunk 13 above)
Comment (manciniedoardo) [reply R/filter_joined.R]: Thanks - I guess same comment applies

**Review by manciniedoardo — APPROVED** [review]
Left one more comment but happy to approve and then merge while it is addressed :) Thanks @bundfussr !

File: R/derive_var_joined_exist_flag.R (hunk 2 above)
Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: Yes, updated

Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: > I also think it still needs a little more clarification because users may think that join_type = "after" could be used since you only need to look after the current record to check for a COVID AE. So you'd need to explain where the before records are needed. Trying to put myself in a user's mindset as i too struggled with this previously.

Do you have a suggestion? I thought "after a COVID AE (ACOVFL == "Y") or up to seven days before a COVID AE" would make it clear. Maybe "records with a duration longer than 30 and where a COVID AE (ACOVFL == "Y") occurred before or up to seven days after the record should be flagged"?
Should we use `ADY.join <= ADY + 7` instead of `ADY >= ADY.join - 7` in `filter_join` then?

Comment (manciniedoardo) [reply R/derive_var_joined_exist_flag.R]: > > I also think it still needs a little more clarification because users may think that join_type = "after" could be used since you only need to look after the current record to check for a COVID AE. So you'd need to explain where the before records are needed. Trying to put myself in a user's mindset as i too struggled with this previously.
> 
> Do you have a suggestion? I thought "after a COVID AE (ACOVFL == "Y") or up to seven days before a COVID AE" would make it clear. Maybe "records with a duration longer than 30 and where a COVID AE (ACOVFL == "Y") occurred before or up to seven days after the record should be flagged"? Should we use `ADY.join <= ADY + 7` instead of `ADY >= ADY.join - 7` in `filter_join` then?

Yes that's great @bundfussr, I think with that explanation it makes it a lot more clear because the combination of "before" and "up to seven days after" then nicely leads to why you need all records and so join_type = "all".

Comment (bundfussr) [reply R/derive_var_joined_exist_flag.R]: Updated
