### PR TITLE
Closes #2147 addressing cran failure

### LINKED ISSUE #2147: URGENT! Failed CRAN Checks: 2023-10-02
CRAN checks for admiral resulted in one or more (WARN,ERROR,NOTE)s:

See the table below for a summary of the checks run by CRAN:

|Flavor                            |Version | Tinstall| Tcheck| Ttotal|Status |Flags |
|:---------------------------------|:-------|--------:|------:|------:|:------|:-----|
|r-devel-linux-x86_64-debian-clang |0.12.1  |    20.40| 397.72| 418.12|OK     |NA    |
|r-devel-linux-x86_64-debian-gcc   |0.12.1  |    15.59| 295.08| 310.67|ERROR  |NA    |
|r-devel-linux-x86_64-fedora-clang |0.12.1  |       NA|     NA| 538.47|ERROR  |NA    |
|r-devel-linux-x86_64-fedora-gcc   |0.12.1  |       NA|     NA| 530.83|ERROR  |NA    |
|r-devel-windows-x86_64            |0.12.1  |    19.00| 333.00| 352.00|ERROR  |NA    |
|r-patched-linux-x86_64            |0.12.1  |    23.06| 382.84| 405.90|OK     |NA    |
|r-release-linux-x86_64            |0.12.1  |    14.08| 383.84| 397.92|OK     |NA    |
|r-release-macos-arm64             |0.12.1  |       NA|     NA| 111.00|OK     |NA    |
|r-release-macos-x86_64            |0.12.1  |       NA|     NA| 257.00|OK     |NA    |
|r-release-windows-x86_64          |0.12.1  |    34.00| 430.00| 464.00|OK     |NA    |
|r-oldrel-macos-arm64              |0.12.1  |       NA|     NA| 151.00|OK     |NA    |
|r-oldrel-macos-x86_64             |0.12.1  |       NA|     NA| 170.00|OK     |NA    |
|r-oldrel-windows-x86_64           |0.12.1  |    23.00| 486.00| 509.00|OK     |NA    |

All details and logs are available here: https://cran.r-project.org/web/checks/check_results_admiral.html

### PR DESCRIPTION
**Pull request by zdz2101**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

File: tests/testthat/test-derive_param_computed.R [hunk 1]
```diff
@@ -343,15 +343,7 @@ test_that("derive_param_computed Test 8: no new observations if a constant param
         AVALU = "kg/m2"
       )
     ),
-    regexp = paste(
-      paste(
-        "The input dataset does not contain any observations fullfiling the filter",
-        "condition (NULL) for the parameter codes (PARAMCD) `HEIGHT`"
```
Comment (zdz2101) [inline tests/testthat/test-derive_param_computed.R:349]: image

Background:

- One of R version 4.4's biggest changes is that `is.atomic(NULL)` now returns `FALSE`, it currently returns `TRUE`.
- In our codebase, for `get_hori_data()` which is used for `derive_param_computed()`, in the section that creates warning messaging, we use a function from `rlang::expr_label()` to assist us with the aesthetically pleasing looking warning messages. 
- `expr_label()` is currently under the lifecycle's `"questioning"` label which means `rlang` themselves had thoughts of:  "a function is no longer certain that a function is the optimal approach, but doesn’t yet know how to do it better"
- We would just need to add ticks around NULL to fix/make sure the test passes for 4.4 **but** it would break the tests for 4.3
- For the purpose of **_our_** code/test in this case its really no big deal, I suggest we just lighten up the restriction not to string match the entire warning message, and just the part that says: "The input dataset does not contain any observations fullfiling the filter" so that it would continue to work for all versions

Comment (zdz2101) [reply tests/testthat/test-derive_param_computed.R:349]: @pharmaverse/admiral

**Comment by bms63** [comment]
We will need to upversion the DESCRIPTION File and make a news blurb.

**Review by bms63 — APPROVED** [review]
