### PR TITLE
Closes #1966 address derive_vars_joined bugs

### LINKED ISSUE #1966: Bug: `derive_vars_joined()`: `*.join` variables are included if `new_vars = NULL`
### What happened?

- If `derive_vars_joined()` is called with `new_vars = NULL` the `*.join` variables are included in the output dataset. 
- Wrong warnings are issued in some cases (see example below).

### Session Information

_No response_

### Reproducible Example

```
myd <- data.frame(day = c(1, 2, 3), val = c(0, 17, 21))
derive_vars_joined(
  myd,
  dataset_add = myd,
  order = exprs(day),
  mode = "last",
  filter_join = day < day.join
)
```
produces
```
  day val day.join val.join
1   1   0        3       21
2   2  17        3       21
3   3  21       NA       NA
```
It should produce an error because `day` and `val` from `dataset_add` are already in `dataset`.

```library(tibble)
library(lubridate)
library(dplyr)
adlb_ast <- tribble(
  ~ADT,         ~ASEQ,
  "2002-01-01", 1,
  "2002-02-02", 2,
  "2002-02-02", 3
) %>%
  mutate(
    STUDYID = "ABC",
    USUBJID = "1",
    ADT = ymd(ADT),
    ADTM = as_datetime(ADT)
  )

adlb_tbili_pbl <- tribble(
  ~ADT,         ~ASEQ,
  "2002-01-01", 4,
  "2002-02-02", 5,
  "2002-02-02", 6
) %>%
  mutate(
    STUDYID = "ABC",
    USUBJID = "1",
    ADT = ymd(ADT),
    ADTM = as_datetime(ADT)
  )

derive_vars_joined(
  adlb_ast,
  dataset_add = adlb_tbili_pbl,
  by_vars = exprs(STUDYID, USUBJID),
  order = exprs(ADTM, ASEQ),
  new_vars = exprs(TBILI_ADT = ADT),
  filter_join = ADT <= ADT.join,
  mode = "first"
)
```
produces
```
# A tibble: 3 × 6
  ADT         ASEQ STUDYID USUBJID ADTM                TBILI_ADT 
  <date>     <dbl> <chr>   <chr>   <dttm>              <date>    
1 2002-01-01     1 ABC     1       2002-01-01 00:00:00 2002-01-01
2 2002-02-02     2 ABC     1       2002-02-02 00:00:00 2002-02-02
3 2002-02-02     3 ABC     1       2002-02-02 00:00:00 2002-02-02
Warning message:
Dataset contains duplicate records with respect to `STUDYID`, `USUBJID`, `tmp_obs_nr_1`, `ADTM` and `ASEQ`
Run `get_duplicates_dataset()` to access the duplicate records 
```

### PR DESCRIPTION
**Pull request by zdz2101**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

File: R/derive_joined.R [hunk 1]
```diff
@@ -399,7 +399,7 @@ derive_vars_joined <- function(dataset,
         suffix = ".join"
       ),
       mode = mode,
-      check_type = check_type
+      check_type = "none"
```
Comment (zdz2101) [inline R/derive_joined.R:402]: @bundfussr This modification addresses the get_duplicates reprex you cited in the issue, though I'm not sure this is the "perfect" solution to it. There are 3 places where `check_type` for the duplicates are being checked, up at line 364 (which is set to "none"), here in line 402 (which is passed through the user in the function call), and passively through `derive_vars_merged()` in line 413 (which is defaulted to "warning"). 

May be important to note, that in our vignette `generic.Rmd`, we have `check_type = "none"` in one of the examples to suppress what would've been a similar warning you have in your reprex, because the default for `check_type` right now in `derive_vars_joined()` is `"warning"`.


image

File: R/derive_joined.R [hunk 2]
```diff
@@ -423,4 +424,10 @@ derive_vars_joined <- function(dataset,
       )
     ) %>%
     remove_tmp_vars()
+
+  if (is.null(original_new_vars)) {
+    data_final <- data_final %>%
```
Comment (zdz2101) [inline R/derive_joined.R:429]: @bundfussr this one addresses the NULL new_vars issue, don't think it's the most "elegant" but should work...?

**Review by bms63 — COMMENTED** [review]
The examples that @bundfussr provided in the issue - is it wise to move them into the tests? 

* Slight misspelling in the news file.

**Review by bms63 — APPROVED** [review]
Thanks for adding the tests!  @bundfussr anymore concerns?

File: R/derive_joined.R (hunk 2 above)
Comment (bundfussr) [reply R/derive_joined.R:429]: I think it is not in line with the documentation and intended behavior. If `new_vars = NULL` is specified, all variables from `dataset_add` should be added. However, in the example from the issue no variable is added. Of course, we can not add all variables because they are already in the input dataset. Thus an error should be issued.

File: R/derive_joined.R (hunk 1 above)
Comment (bundfussr) [reply R/derive_joined.R:402]: This line should not be changed. Otherwise, no message is issued if the selected observation is not unique. Consider for example
```
derive_vars_joined(
  adlb_ast,
  dataset_add = adlb_tbili_pbl,
  by_vars = exprs(STUDYID, USUBJID),
  order = exprs(ADT),
  new_vars = exprs(TBILI_ADT = ADT, TBILI_SEQ = ASEQ),
  filter_join = ADT <= ADT.join,
  mode = "first"
)
```
with the datasets from the second example in the issue. Here a warning should be issued because the first TBILI assessment at or after the AST assessment is not unique for `ASEQ %in% c(2, 3)`.

**Review by bundfussr — CHANGES_REQUESTED** [review]

File: R/derive_joined.R (hunk 1 above)
Comment (zdz2101) [reply R/derive_joined.R:402]: If thats the case, is the example in the `generic.Rmd` a little misleading then? If it weren't toggled to `check_type = "none"` there would be a warning. I also think there is some overall confusion with how `order` is handled in general which might be the source of the troubles here

image

In general, `!!!chr2vars(names(order))` does **not** select columns so the `common_vars` statement a little further down can be inconsistent, depending if the user plugged in a function and used a var-val declaration e.g `convert_dtc_to_dt()` inside order

File: R/derive_joined.R (hunk 2 above)
Comment (zdz2101) [reply R/derive_joined.R:429]: So in the case of all variables already in the input dataset, the desired result would be an error and no-return object at all?

**Review by manciniedoardo — APPROVED** [review]

File: R/derive_joined.R (hunk 2 above)
Comment (bundfussr) [reply R/derive_joined.R:429]: Yes, or more precise, if _any_ of the variables specified for `new_vars` is already in the input dataset, the function should stop with an error.

File: R/derive_joined.R (hunk 1 above)
Comment (bundfussr) [reply R/derive_joined.R:402]: Specifying `check_type = "none"` in the example makes sense because only the maximum severity is added as new variable. If there are multiple observations with the maximum severity, it doesn't matter which one is used.

Regarding `order`, we need to more comments to the code. The purpose of the `mutate()` call is to create variables for named expressions in `order`. Then these can be used in `join_vars` or the filter condition.
You are right that `!!!chr2vars(names(order))` is not correct. We may lose the variables used in the expressions of `order`. I think it should be replaced by `!!!replace_values_by_names(extract_vars(order))`.

File: R/derive_joined.R (hunk 2 above)
Comment (zdz2101) [reply R/derive_joined.R]: Please see updated `if (is.null(new_vars))` at line 353 that implements suggestion and updated test with the corresponding messaging

File: R/derive_joined.R [hunk 3]
```diff
@@ -352,6 +352,18 @@ derive_vars_joined <- function(dataset,
...
+    if (any(new_vars %in% preexisting_vars_no_by_vars)) {
+      err_msg <- sprintf(
+        paste(
+          "The following columns in `dataset_add` have naming conflicts with `dataset`,\n",
+          "please make the appropriate modifications to `new_vars`, with respect to:\n%s"
+        ),
+        enumerate(vars2chr(new_vars[which(new_vars %in% preexisting_vars_no_by_vars)]))
+      )
+      abort(err_msg)
+    }
```
Comment (bundfussr) [inline R/derive_joined.R:366]: The check should also be performed if `new_vars` is not `NULL`. For example
```
> myd <- data.frame(day = c(1, 2, 3), val = c(0, 17, 21))
> derive_vars_joined(
+     myd,
+     dataset_add = myd,
+     new_vars = exprs(val),
+     order = exprs(day),
+     mode = "last",
+     filter_join = day < day.join
+ )
  day val val.join
1   1   0       21
2   2  17       21
3   3  21       NA
```
should produce an error instead of adding `val.join`.

File: R/derive_joined.R [hunk 4]
```diff
@@ -394,7 +406,7 @@ derive_vars_joined <- function(dataset,
       data_return,
       by_vars = expr_c(by_vars_left, tmp_obs_nr),
       order = add_suffix_to_vars(
-        replace_values_by_names(order),
+        replace_values_by_names(extract_vars(order)),
```
Comment (bundfussr) [inline R/derive_joined.R:409]: This should not be changed. Otherwise, expressions are replaced by the variables contributing to the expression. Consider for example
```
> myd <- data.frame(day = c(1, 2, 3), val = c(0, 17, 21))
> derive_vars_joined(
+     myd,
+     dataset_add = myd,
+     new_vars = exprs(first_val = val),
+     join_vars = exprs(day),
+     order = exprs(-day),
+     mode = "last",
+     filter_join = day < day.join
+ )
  day val first_val
1   1   0        21
2   2  17        21
3   3  21        NA
```
It should produce
```
  day val first_val
1   1   0        17
2   2  17        21
3   3  21        NA
```

File: tests/testthat/test-derive_joined.R [hunk 5]
```diff
@@ -242,3 +242,66 @@ test_that("derive_vars_joined Test 7: new_vars expressions using variables from
     keys = c("USUBJID", "AESEQ")
   )
 })
+## Test 8: NULL new_vars will still remove .join columns ----
+test_that("derive_vars_joined Test 8: NULL new_vars will still remove .join columns", {
```
Comment (bundfussr) [inline tests/testthat/test-derive_joined.R:246]: Should we update the title to something like "error if new_vars are already in dataset"?

**Review by bundfussr — CHANGES_REQUESTED** [review]

File: R/derive_joined.R (hunk 4 above)
Comment (zdz2101) [reply R/derive_joined.R]: This has been addressed, should I add this example as an additional test?

File: R/derive_joined.R (hunk 3 above)
Comment (zdz2101) [reply R/derive_joined.R:366]: Removing the if NULL bracket just about broke every-other test/use case in the vignettes, so I'm not entirely sure we want to do this without making it drastically change our useability

File: R/derive_joined.R (hunk 4 above)
Comment (bundfussr) [reply R/derive_joined.R]: Yes, I think this would be helpful for updates in the future.

File: R/derive_joined.R (hunk 3 above)
Comment (bundfussr) [reply R/derive_joined.R:366]: Sorry, I did not mean to remove the `if` condition but move the highlighted part out of the bracket:
```
  if (is.null(new_vars)) {
    new_vars <- chr2vars(colnames(dataset_add))
  }
  preexisting_vars <- chr2vars(colnames(dataset))
  preexisting_vars_no_by_vars <- preexisting_vars[which(!(preexisting_vars %in% by_vars))]
  duplicates <- intersect(replace_values_by_names(new_vars), preexisting_vars_no_by_vars)
  if (length(duplicates) > 0) {
    err_msg <- sprintf(
      paste(
        "The following columns in `dataset_add` have naming conflicts with `dataset`,\n",
        "please make the appropriate modifications to `new_vars`, with respect to:\n%s"
      ),
      enumerate(vars2chr(duplicates))
    )
    abort(err_msg)
  }
```
I tweaked the check code above to cover cases where variables in `new_vars` are renamed.

Comment (zdz2101) [reply R/derive_joined.R]: Thanks! Adopted this into the newest commit

File: R/derive_joined.R (hunk 4 above)
Comment (zdz2101) [reply R/derive_joined.R]: Added!

**Review by bundfussr — APPROVED** [review]
