### PR TITLE
887 bsa fix documentation - close #887

### LINKED ISSUE #887: Check BSA formula
Check BSA formula

### PR DESCRIPTION
**Pull request by esimms999-gsk**
…orrect. It has now been changed from:

sqrt(height(cm) * weight(kg)) / 3600

to:

sqrt(height * weight / 3600) 

... and a note has been added that HEIGHT is expected in cm and WEIGHT is expected in kg.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://roche-gsk.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://roche-gsk.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://roche-gsk.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::documents()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://roche-gsk.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

File: R/derive_advs_params.R [hunk 1]
```diff
@@ -208,9 +208,10 @@ compute_map <- function(diabp, sysbp, hr = NULL) {
 #'   the input dataset after restricting it by the filter condition (`filter`
 #'   parameter) and to the parameters specified by `HEIGHT` and `WEIGHT`.
 #'
-#' @param method Derivation method to use:
+#' @param method Derivation method to use. Note that HEIGHT is expected
```
Comment (bms63) [inline R/derive_advs_params.R:211]: I think HEIGHT and WEIGHT should have backticks.

**Review by bms63 — CHANGES_REQUESTED** [review]
Hey Eric!  Thanks for update.  I assigned myself so we could get this in the next release.  Can you make quick fix?

**Review by bms63 — APPROVED** [review]
Looks good!
