### PR TITLE
Closes #2326 check_type documentation is updated for argument details.

### LINKED ISSUE #2326: `check_type` in `derive_vars_merged()` not working
### Background Information

`check_type` in `derive_vars_merged()` is not working as expected when `order` is `NULL`
example: `check_type = warning` but an error is returned 
```r
adsl <- tribble(
  ~USUBJID, ~SEX, ~COUNTRY,
  "ST42-1", "F",  "AUT"
)

advs <- tribble(
  ~USUBJID, ~PARAMCD, ~AVISIT,    ~AVISITN, ~AVAL,
  "ST42-1", "WEIGHT", "BASELINE",        0,    66,
  "ST42-1", "WEIGHT", "WEEK 2",          1,    68
)

derive_vars_merged(
  adsl,
  dataset_add = advs,
  by_vars = exprs(USUBJID),
  new_vars = exprs(WEIGHT = AVAL),
  check_type = "warning"
)
```

error message:
```r
Error in `signal_duplicate_records()`:
! Dataset `dataset_add` contains duplicate records with respect to `USUBJID`
Run `get_duplicates_dataset()` to access the duplicate records
Run `rlang::last_trace()` to see where the error occurred.
```

### Definition of Done

add `cnd_type = check_type` when calling the following `signal_duplicate_records`

https://github.com/pharmaverse/admiral/blob/16671ee64d124e9eff26bfa7a776442ad610ed84/R/derive_merged.R#L375-L379

### PR DESCRIPTION
**Pull request by Lina2689**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF version of it to the same folder.
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
Thanks @Lina2689 - I'm just wondering if we need a test set up to make sure this is behaving appropriately??  @bundfussr WDYT??

Perhaps there is already one??

File: R/derive_merged.R [hunk 1]
```diff
@@ -127,6 +127,10 @@
 #'   if the observations of the (restricted) additional dataset are not unique
 #'   with respect to the by variables and the order.
 #'
+#'   If the `check_type` argument is specified, `order` must be set to a non-null value.
```
Comment (bundfussr) [inline R/derive_merged.R:130]: This is not true. I would remove this sentence.

File: R/derive_merged.R [hunk 2]
```diff
@@ -127,6 +127,10 @@
...
+#'
+#'   If the `order` argument is not specified, the `check_type` argument is ignored.
```
Comment (bundfussr) [inline R/derive_merged.R:132]: We should say what "ignored" means. I would add something like "I.e., if the observations of the (restricted) additional dataset are not unique with respect to the by variables, an error is issued."

**Review by bundfussr — CHANGES_REQUESTED** [review]

**Comment by bundfussr** [comment]
> Thanks @Lina2689 - I'm just wondering if we need a test set up to make sure this is behaving appropriately?? @bundfussr WDYT??
> 
> Perhaps there is already one??

Yes, a test for the case that `order` is not specified and duplicates in `dataset_add` with respect to `by_vars` is a good idea.

File: R/derive_merged.R (hunk 2 above)
Comment (Lina2689) [reply R/derive_merged.R:132]: Thanks @bundfussr , I will modify the sentence.

**Comment by Lina2689** [comment]
@bundfussr & @bms63 , I have added test cases when order is not specified and also updated the description in header. Can you please review and let me know if anything needs to be updated.

File: tests/testthat/test-derive_merged.R [hunk 3]
```diff
@@ -631,3 +631,48 @@ test_that("derive_var_merged_summary Test 23: deprecation warning", {
...
+test_that("derive_vars_merged Test 24: error if not unique w.r.t the by variables and
+          the order is not specified", {
+  expect_error(
+    actual <- derive_vars_merged(advs,
+      dataset_add = adsl2,
+      by_vars = exprs(STUDYID, USUBJID = ID),
+      order = NULL,
+      check_type = "error"
+    ),
+    regexp = NULL
```
Comment (bundfussr) [inline tests/testthat/test-derive_merged.R:646]: Please specify a value for `regexp` which ensures that the expected error is issued. Otherwise, any error is accepted.

**Review by bundfussr — CHANGES_REQUESTED** [review]

**Review by bundfussr — APPROVED** [review]

**Review by bms63 — APPROVED** [review]
Thanks @Lina2689 !!!!!!  

This is your first official PR?!?!  Congrats if so!!!!!!!! A big accomplishment!!
