### PR TITLE
Closes #2091 fixing deprecation messaging in `derive_param_doseint()`

### LINKED ISSUE #2091: Bug: Proper deprecation of `derive_param_computed()`
### What happened?

image

### Session Information

_No response_

### Reproducible Example

Look into `ad_adex.R` template

### PR DESCRIPTION
**Pull request by zdz2101**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by zdz2101** [comment]
@bms63 the `analysis_value` function argument was still being passed through `derive_param_doseint()` which is a wrapper for `derive_param_computed()` I think this should do the trick

**Comment by StefanThoma** [comment]
There was some duplicate deprecation code in derive_param_computed. It should be fixed now, please check.

File: R/derive_param_computed.R [hunk 1]
```diff
@@ -293,14 +293,6 @@ derive_param_computed <- function(dataset = NULL,
...
                                   keep_nas = FALSE) {
   assert_vars(by_vars)
-  if (!missing(analysis_var)) {
-    deprecate_warn(
-      "0.12.0",
-      "derive_param_computed(analysis_var = )",
-      "derive_param_computed(set_values_to = )"
-    )
-  }
-  analysis_var <- assert_symbol(enexpr(analysis_var))
```
Comment (bundfussr) [inline R/derive_param_computed.R:303]: I think we should not remove this part because otherwise the following does not issue a deprecation warning.
```
> derive_param_computed(
+   advs,
+   by_vars = exprs(USUBJID, VISIT),
+   parameters = c("SYSBP", "DIABP"),
+   analysis_var = CHR,
+   set_values_to = exprs(
+     AVAL = (AVAL.SYSBP + 2 * AVAL.DIABP) / 3,
+     PARAMCD = "MAP",
+     PARAM = "Mean Arterial Pressure (mmHg)",
+     AVALU = "mmHg"
+   )
+ )
```

**Review by bundfussr — CHANGES_REQUESTED** [review]

File: R/derive_param_computed.R (hunk 1 above)
Comment (StefanThoma) [reply R/derive_param_computed.R:303]: I was a bit confused by analysis_var and analysis_value, but I think I fixed it now, hopefully!

Comment (bundfussr) [reply R/derive_param_computed.R:303]: Have you committed your fix?

Comment (StefanThoma) [reply R/derive_param_computed.R:303]: Will be up in a minute, still running check()

**Review by bundfussr — APPROVED** [review]
